name: Deploy to EC2

on:
  push:
    branches: [ main ]  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Gitチェックアウト
        uses: actions/checkout@v3

      - name: PHPとComposerをセットアップ
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extension-csv: mbstring, intl, pdo_mysql

      - name: Composer install
        run: composer install --no-dev --optimize-autoloader

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: npm installとビルド
        run: |
          npm install
          npm run build

      - name: デプロイのためにSSH接続
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 52.197.144.4
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /path/to/shift-app
            git pull origin main
            composer install --no-dev --optimize-autoloader
            npm install
            npm run build
            php artisan migrate --force
            php artisan config:cache
            # サービスの再起動（例: supervisorctl restart shift-app）
