name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Gitチェックアウト
        uses: actions/checkout@v3

      - name: PHPとComposerをセットアップ
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extension-csv: mbstring, intl, pdo_mysql

      - name: Composer install
        run: composer install --no-dev --optimize-autoloader

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: npm installとビルド
        run: |
          npm install
          npm run build

      - name: ビルド成果物をEC2へ転送（例：public/build）
        uses: appleboy/scp-action@v0.1.5
        with:
          host: 52.197.144.4
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "public/build"
          target: "/var/www/shift-app/public"

      - name: アプリコードをEC2に転送
        uses: appleboy/scp-action@v0.1.5
        with:
          host: 52.197.144.4
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."  # 必要に応じて制限してね！
          target: "/var/www/shift-app"

      - name: EC2でアプリケーション更新処理実行
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 52.197.144.4
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/shift-app
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            # サービス再起動（例: sudo supervisorctl restart shift-app）
